[package]
name = "gpt-cat"
authors = ["Anivie"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
time = "0.3.36"
thiserror = "1.0.63"

async-stream = "0.3.5"
tokio-util = "0.7.11"

bytes = "1.7.1"
rustls = "0.23.12"
rustls-pemfile = "2.1.3"

log = "0.4.22"
fast_log = { version = "1.7.3", features = ["lz4"] }
colored = "2.1.0"
color-eyre = { version = "0.6.3", default-features = false }

parking_lot = { version = "0.12.3", features = ["send_guard"] }
dashmap = { version = "6.0.0", features = ["inline", "serde"] }

serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
notify = "6.1.1"
rayon = "1.10.0"

uuid = { version = "1.10.0", features = ["v4"] }
rand = "0.9.0-alpha.2"

tiktoken-rs = "0.5.9"
anyhow = "1.0.86"
base64 = "0.22.1"

futures = "0.3.30"
futures-util = "0.3.30"

mime = "0.3.17"
rust_decimal = "1.35.0"

sqlx-postgres = { version = "0.8.0", features = ["json", "migrate"] }

[dependencies.sqlx]
version = "0.8.0"
default-features = false
features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "time", "rust_decimal"]

[dependencies.tower-http]
version = "0.5.2"
features = ["compression-full", "cors"]

[dependencies.axum]
git = "https://github.com/tokio-rs/axum.git"
features = ["tokio", "json", "macros"]

[dependencies.axum-server]
version = "0.7.1"
features = ["tls-rustls"]

[dependencies.tokio]
version = "1.39.2"
features = ["full"]

[dependencies.reqwest]
version = "0.12.5"
default-features = false
features = ["gzip", "deflate", "brotli", "json", "stream", "socks", "rustls-tls"]