[package]
name = "gpt-cat"
authors = ["Anivie"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
time = "0.3.36"
thiserror = "1.0.61"

async-stream = "0.3.5"
tokio-stream = "0.1.15"
tokio-channel = "0.1.0"
tokio-util = "0.7.11"

bytes = "1.6.0"
rustls = "0.23.10"
rustls-pemfile = "2.1.2"

log = "0.4.22"
fast_log = { version = "1.6.16", features = ["lz4"] }
colored = "2.1.0"
color-eyre = { version = "0.6.3", default-features = false }

parking_lot = { version = "0.12.3", features = ["send_guard"] }
dashmap = { version = "6.0.0", features = ["inline", "serde"] }
blake3 = "1.5.1"

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
notify = "6.1.1"
rayon = "1.10.0"

uuid = { version = "1.9.1", features = ["v4"] }
rand = "0.9.0-alpha.1"

tiktoken-rs = "0.5.9"
anyhow = "1.0.86"
base64 = "0.22.1"

futures = "0.3.30"
futures-util = "0.3.30"

mime = "0.3.17"
rust_decimal = "1.35.0"

[dependencies.tower-http]
version = "0.5.2"
features = ["compression-full", "cors"]

[dependencies.axum]
git = "https://github.com/tokio-rs/axum.git"
features = ["tokio", "json", "macros"]

[dependencies.axum-server]
git = "https://github.com/programatik29/axum-server.git"
features = ["tls-rustls"]

[dependencies.sea-orm]
version = "1.0.0-rc.7"
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]

[dependencies.tokio]
version = "1.38.0"
features = ["full"]

[dependencies.reqwest]
version = "0.12.5"
default-features = false
features = ["gzip", "deflate", "brotli", "json", "stream", "socks", "rustls-tls"]