//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_disabled: bool,
    pub use_proxy: Option<String>,
    pub username: Option<String>,
    pub password: String,
    pub endpoint: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_list::Entity")]
    ChatList,
}

impl Related<super::chat_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
