//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "public_command")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub command: String,
    #[sea_orm(column_type = "Text")]
    pub describe: String,
    #[sea_orm(column_type = "Text")]
    pub prompt: String,
    pub is_disable: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
